### ISSUE TITLE
Definition horizontal lists are broken

### ISSUE THREAD

**Issue by diosney** [zavoloklom/material-design-typography#2]
May I recomend to stick with bootstrap default overall styles and apply only font, padding, margin customizations?

Below is the offending rule:

``` css

.dl-horizontal {
  @media (min-width: 768px) {

    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: start;
    -webkit-align-items: flex-start;
    -ms-flex-align: start;
    align-items: flex-start;

    dt {
      width: 180px;
      margin-right: @padding-base;
      text-align: right;
      .text-overflow();
    }
    dd {
      -webkit-box-flex: 1;
      -webkit-flex: 1;
      -ms-flex: 1;
      flex: 1;
    }
  }
}
```
